### ISSUE TITLE
Relicensing to a standard MIT license?

### ISSUE THREAD

**Issue by nbren12** [samhatfield/speedy.f90#13]
Hi Sam. I was considering using this awesome simple GCM for some work, but I'm not sure I can because the license only authorizes use for "research, educational and other non-commercial purposes". Otherwise it looks like a standard MIT license, so I just wanted to check that this was intentional. 

These days, more and more climate research is happening in places like AI2 and NVIDIA that have lawyers looking into this stuff. Typically we will have blanket approval to use standard MIT, Apache, BSD etc, but need special approvals for custom text...I think this is why most of the python ecosystem for example uses standard open source licenses verbatim. In this case, I doubt we would get such approval. Right now we are just planning to use it for research purposes/publishing, but one never knows.

We were inspired by [this paper](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021MS002712?af=R) which hybridizes speedy with an ML system. Happy to talk more about the research idea/work. Thanks!

**Comment by samhatfield** [comment]
Hey Noah! We came up with this license in discussion with Franco Molteni and Fred Kucharski, who wrote [the original SPEEDY model](http://users.ictp.it/~kucharsk/speedy-net.html) this modern Fortran version is based on. I suggested a plain MIT license, and they requested that I add the non-commercial clause. I can't remember exactly what their rationale was, but it was basically what you'd expect: a concern that the code (in particular the physics) would be used for commercial gain by a private entity.

In fact we've been through this already with Stephan Hoyer at Google. A non-standard license was pretty much out of the question for Google's lawyers. He (and Peter Norgaard and others) had the same concerns you have, and we even organised some discussions with Franco and Fred. In the end we couldn't persuade them to fully open the code, but Fred was at least kind enough to publish the physical parametrisations of the original SPEEDY under an MIT license (follow the above link and scroll down to "For a package containing exclusively the SPEEDY physical parameterization..."). I made a stab at wrapping those into a [standalone drivable physics package in modern Fortran](https://github.com/samhatfield/speedy_physics.f90), but have put it aside for now as I no longer needed it.

So unfortunately it's not straightforward to switch to a standard open license - that would be up to Franco and Fred. You're welcome to contact them if you think you have something persuasive to say that we couldn't :)

**Comment by nbren12** [comment]
Thanks for this history, Sam. I suspected that there was some intent behind the modified language. I just wanted to confirm since 9/10 times these licensing issues are unintentional. I think we will avoid hitting the same brick walls as Stephan.

Would be nice to build a simple spectral solver without these licensing issues, but clearly that is out of the scope of this repo. Feel free to close this issue.

**Comment by samhatfield** [comment]
No problem. If it's just the spectral component you're interested in, you might like to take at look at [SpeedyWeather.jl](https://github.com/milankl/SpeedyWeather.jl), whose dycore is strongly influenced by speedy.f90. Good luck!
